defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}

name: robomimic_can_vgd_guided_${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
logdir: ${log_dir}/robomimic-vgd/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ./dppo/log/robomimic-pretrain/can/can_pre_diffusion_mlp_ta4_td20/2024-06-28_13-29-54/checkpoint/state_5000.pt
offline_data_path: ./dppo/log/robomimic/can_test/train_offline.npz
dppo_path: ./dppo
normalization_path: ./dppo/log/robomimic/${env_name}/normalization.npz

seed: 1
device: cuda:0
use_wandb: True
torch_compile: False
env_name: can
log_dir: ./logs
obs_dim: 23
action_dim: 7
cond_steps: 1
act_steps: 4
load_offline_data: False
deterministic_eval: False
record_eval_noise: True
record_eval_episodes: 5
stop_after_episodes: -1

eval_interval: 1000
num_evals: 200
save_model_interval: 100000
save_replay_buffer: False

env:
  n_envs: 8
  n_eval_envs: 25
  name: ${env_name}
  max_episode_steps: 300
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 1
  reward_offset: 1
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    'object']
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  project: optimal_control_rl_project
  run: vgd_dyna_can_ddim${model.ddim_steps}_seed${seed}
  group: vgd_dyna_can_ddim${model.ddim_steps}

train:
  use_dynamic_guidance: True
  tau: 0.005
  actor_lr: 5e-4
  batch_size: 512
  train_freq: 1
  utd: 20
  init_rollout_steps: 1501
  use_layer_norm: True
  layer_size: 2048
  num_layers: 3
  discount: 0.999
  n_critics: 4
  critic_backup_combine_type: min
  target_uncertainty: 0.01
  uncertainty_beta: 1.0
  # Guided denoising params (guidance-only + x0)
  guidance_lambda: 0.005
  guidance_warmup_steps: 0
  guidance_time_anneal: off
  guidance_last_k_steps: 3
  guidance_decode_steps: -1

model:
  _target_: model.diffusion.diffusion_eval.DiffusionEval
  ft_denoising_steps: 0
  predict_epsilon: True
  denoised_clip_value: 1.0
  randn_clip_value: 3
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [512, 512, 512]
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${act_steps}
    action_dim: ${action_dim}
  horizon_steps: ${act_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: 20
  device: ${device}
  use_ddim: True
  ddim_steps: 8
  controllable_noise: True


